In [1]:
import pandas as pd
import glob

In [2]:
coordinates = pd.read_csv("../gozlem_istasyonu/awos_beus_dec.csv")
coordinates.head()

  Sıra No İstasyon Adı   Latitude  Longitude
0   awos1        Çanta  41.100000  28.083333
1   awos2    Çavuşbaşı  41.083333  29.150000
2   awos3    Olimpiyat  41.100000  28.766667
3   awos4       Terkos  41.316667  28.666667
4   awos5     Hadımköy  41.050000  28.633333

In [3]:
weather_data = pd.concat([pd.read_csv(i) for i in glob.glob("../hava_durumu/*")]).reset_index(drop=True)

In [4]:
negative_value_prep = weather_data[weather_data['AVERAGE_PRECIPITATION'] == -99.00000].index

weather_data.drop(negative_value_prep, inplace = True)

In [5]:
negative_value_temp = weather_data[weather_data['AVERAGE_ROAD_TEMPERATURE'] == -99.00000].index

weather_data.drop(negative_value_temp, inplace = True)

In [6]:
weather_data

,DATE_TIME,OBSERVATORY_NAME,SENSOR_TYPE,MINIMUM_TEMPERATURE,MAXIMUM_TEMPERATURE,AVERAGE_TEMPERATURE,MINIMUM_HUMIDITY,MAXIMUM_HUMIDITY,AVERAGE_HUMIDITY,MINIMUM_WIND,...,AVERAGE_DIRECTIONOFWIND,MINIMUM_PRECIPITATION,MAXIMUM_PRECIPITATION,AVERAGE_PRECIPITATION,MINIMUM_ROAD_TEMPERATURE,MAXIMUM_ROAD_TEMPERATURE,AVERAGE_ROAD_TEMPERATURE,MINIMUM_FELT_TEMPERATURE,MAXIMUM_FELT_TEMPERATURE,AVERAGE_FELT_TEMPERATURE
0,2020-05-23 00:00:00,BAYRAMOGLU_TUZLA,ICING_SENSOR,10.74,11.42,11.06914,77.00,81.10,79.36069,0.000,...,115.74138,0.0,0.00,0.00000,11.0,11.6,11.31724,10.88,12.90,11.90483
1,2020-05-20 13:00:00,ESENLER,ICING_SENSOR,30.04,31.28,30.49544,50.25,53.92,52.42070,1.250,...,75.87719,0.0,0.00,0.00000,41.8,43.3,42.61053,31.64,33.17,32.22632
2,2020-05-27 22:00:00,BAYRAMOGLU_TUZLA,ICING_SENSOR,12.44,12.84,12.63566,84.00,85.70,84.83019,0.000,...,145.30189,0.0,0.12,0.00660,13.3,13.8,13.60377,11.90,14.18,13.11509
3,2020-05-27 23:00:00,BAYRAMOGLU_TUZLA,ICING_SENSOR,12.23,12.57,12.43627,85.90,88.80,87.76441,0.000,...,202.15254,0.0,0.13,0.01610,12.9,13.3,13.16949,12.23,14.20,13.37322
4,2020-05-23 01:00:00,BAYRAMOGLU_TUZLA,ICING_SENSOR,10.47,10.81,10.58386,81.40,82.20,81.78421,0.000,...,137.92982,0.0,0.00,0.00000,10.6,11.0,10.77193,10.56,12.36,11.52930
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
738788,2020-11-18 00:00:00,CAMLICA_TUNEL_G,ICING_SENSOR,11.22,11.75,11.53678,84.40,88.50,86.36271,0.931,...,34.62712,0.0,0.00,0.00000,9.0,9.2,9.07797,10.86,12.54,11.55136
738790,2020-11-18 02:00:00,ZEKERIYAKOY,ICING_SENSOR,11.21,11.89,11.48917,91.00,97.70,95.74333,0.610,...,117.98333,0.0,0.31,0.03750,9.5,9.9,9.70167,11.14,13.34,12.01650
738796,2020-11-21 18:00:00,AHL_BAKIRKOY,ICING_SENSOR,11.14,11.48,11.30574,77.52,83.60,81.46611,1.650,...,88.01852,0.0,0.16,0.00296,9.9,10.2,10.09074,9.51,11.68,10.67463
738801,2020-11-30 15:00:00,HALIC,ICING_SENSOR,9.58,10.37,10.07945,82.60,86.30,83.76182,0.690,...,125.03636,0.0,0.44,0.05200,11.9,13.1,12.74727,7.26,11.31,9.57491
738802,2020-11-14 11:00:00,PENDIK,ICING_SENSOR,12.80,13.41,13.18850,80.40,83.60,81.69000,0.000,...,227.56667,0.0,0.02,0.00133,14.4,14.9,14.57333,12.80,14.80,13.21383

In [7]:
coordinates["istasyon_adi"] = coordinates["İstasyon Adı"].apply(lambda x : x.lower())
coordinates.head()

  Sıra No İstasyon Adı   Latitude  Longitude istasyon_adi
0   awos1        Çanta  41.100000  28.083333        çanta
1   awos2    Çavuşbaşı  41.083333  29.150000    çavuşbaşı
2   awos3    Olimpiyat  41.100000  28.766667    olimpiyat
3   awos4       Terkos  41.316667  28.666667       terkos
4   awos5     Hadımköy  41.050000  28.633333     hadımköy

In [8]:
weather_data["istasyon_adi"] = weather_data["OBSERVATORY_NAME"].apply(lambda x : " ".join(x.split("_")).strip().lower())

In [9]:
weather_data.head()
weather_data.columns

Index(['DATE_TIME', 'OBSERVATORY_NAME', 'SENSOR_TYPE', 'MINIMUM_TEMPERATURE',
       'MAXIMUM_TEMPERATURE', 'AVERAGE_TEMPERATURE', 'MINIMUM_HUMIDITY',
       'MAXIMUM_HUMIDITY', 'AVERAGE_HUMIDITY', 'MINIMUM_WIND', 'MAXIMUM_WIND',
       'AVERAGE_WIND', 'MINIMUM_DIRECTIONOFWIND', 'MAXIMUM_DIRECTIONOFWIND',
       'AVERAGE_DIRECTIONOFWIND', 'MINIMUM_PRECIPITATION',
       'MAXIMUM_PRECIPITATION', 'AVERAGE_PRECIPITATION',
       'MINIMUM_ROAD_TEMPERATURE', 'MAXIMUM_ROAD_TEMPERATURE',
       'AVERAGE_ROAD_TEMPERATURE', 'MINIMUM_FELT_TEMPERATURE',
       'MAXIMUM_FELT_TEMPERATURE', 'AVERAGE_FELT_TEMPERATURE', 'istasyon_adi'],
      dtype='object')

In [10]:
#koordinatları bilinen istasyonlar ile hava durumu verisi ile eşleşen isimlerin tutulduğu dict.
station_dict = {"ahl-bakırköy":"ahl bakirkoy",
"akom":"akom",
"alibahadır":"alibahadir",
"arnavutköy":"arnavutkoy",
"ataşehir":"atasehir",
"b.çekmece-s virajları":"b cekmece svirajlari",
"bahçeşehir-ispartakule":"bahcesehir i kule",
"bayramoğlu-tuzla":"bayramoglu tuzla",
"başakşehir":"basaksehir",
"beykoz":"beykoz",
"beylikdüzü-haramidere":"beylikduzu h dere",
"beşiktaş-yıldız":"besiktas yildiz",
"büyükada":"buyukada",
"d100 silivri":['silivri orman sahasi','silivri mgm'],
"durusu":"durusu",
"esenler":"esenler",
"g.o.paşa":"g o pasa",
"hacıosman-sarıyer":"haciosman sariyer",
"hadımköy":"hadimkoy",
"haliç":"halic",
"i̇stoç-mahmutbey":"istoc mahmutbey",
"kamiloba":"kamiloba",
"kartal-u.mumcu":"kartal u mumcu",
"kınalı":"kinali",
"maslak-i̇tü":"maslak itu",
"odeyeri":"odeyeri",
"olimpiyat":"olimpiyat",
"paşaköy":"pasakoy",
"pendik":"pendik",
"riva tunel güney":"riva tunel g",
"riva tunel kuzey":"riva tunel k",
"sabiha gökçen":"sabihagokcen",
"selimpaşa-kavaklı":"selimpasa kavakli",
"subaşı":"subasi",
"süreyyapaşa":"sureyyapasa",
"tem çatalca gişeler":["catalca","catalca mgm"],
"terkos":"terkos",
"tuzla piyade okulu":["tuzla mgm","bayramoglu tuzla"],
"uskumruköy":"uskumrukoy",
"zekeriyaköy":"zekeriyakoy",
"zincirlikuyu":"zincirlikuyu",
"çamlıca tunel güney":"camlica tunel g",
"çamlıca tunel kuzey":"camlica tunel k",
"çamlıca-libadiye":"camlica libadiye",
"çanta":"canta",
"çavuşbaşı":"cavusbasi",
"çiftalan":"ciftalan",
"ömerli":"omerli",
"ümraniye":"umraniye",
"şile":"sile",
"şile yolu ömerli":["omerli","sile","sile 2","sile darlik"]}

In [11]:
coordinates["eslesen_istasyonlar"] = coordinates.istasyon_adi.apply(lambda y: 1 if y in station_dict else 0)

coordinates = coordinates[coordinates.eslesen_istasyonlar == 1]

In [12]:
from tqdm import tqdm
tqdm.pandas()
weather_data = weather_data[weather_data.istasyon_adi.isin(set(coordinates.istasyon_adi))].copy()
weather_data.loc[:,"latitude"] = weather_data.istasyon_adi.progress_apply(lambda x: coordinates[coordinates.istasyon_adi == x].Latitude.values[0])
weather_data.loc[:,"longitude"] = weather_data.istasyon_adi.progress_apply(lambda x: coordinates[coordinates.istasyon_adi == x].Longitude.values[0])

100%|██████████| 51751/51751 [00:15<00:00, 3403.93it/s]
100%|██████████| 51751/51751 [00:14<00:00, 3500.85it/s]

In [13]:
import numpy as np
weather_data.MINIMUM_DIRECTIONOFWIND = weather_data.MINIMUM_DIRECTIONOFWIND.astype(np.float64)
weather_data.MAXIMUM_DIRECTIONOFWIND = weather_data.MAXIMUM_DIRECTIONOFWIND.astype(np.float64)
weather_data.SENSOR_TYPE = pd.factorize(weather_data.SENSOR_TYPE)[0]
weather_data.istasyon_adi = pd.factorize(weather_data.istasyon_adi)[0]

In [14]:
weather_data

,DATE_TIME,OBSERVATORY_NAME,SENSOR_TYPE,MINIMUM_TEMPERATURE,MAXIMUM_TEMPERATURE,AVERAGE_TEMPERATURE,MINIMUM_HUMIDITY,MAXIMUM_HUMIDITY,AVERAGE_HUMIDITY,MINIMUM_WIND,...,AVERAGE_PRECIPITATION,MINIMUM_ROAD_TEMPERATURE,MAXIMUM_ROAD_TEMPERATURE,AVERAGE_ROAD_TEMPERATURE,MINIMUM_FELT_TEMPERATURE,MAXIMUM_FELT_TEMPERATURE,AVERAGE_FELT_TEMPERATURE,istasyon_adi,latitude,longitude
1,2020-05-20 13:00:00,ESENLER,0,30.040,31.28,30.49544,50.25,53.92,52.42070,1.250,...,0.00000,41.8,43.3,42.61053,31.64,33.17,32.22632,0,41.044633,28.892364
5,2020-05-02 20:00:00,ZINCIRLIKUYU,0,17.180,19.16,17.81263,56.50,64.58,61.69965,1.490,...,0.02158,23.1,25.0,24.49649,17.48,20.21,18.37000,1,41.066714,29.013019
15,2020-05-03 01:00:00,ZINCIRLIKUYU,0,14.440,15.33,14.76423,79.66,85.20,82.53308,0.000,...,0.00000,18.5,18.9,18.71923,14.85,17.09,15.86423,1,41.066714,29.013019
22,2020-05-26 11:00:00,ESENLER,0,20.040,20.72,20.31083,50.88,54.28,52.25583,1.410,...,0.00000,34.7,44.0,39.40000,20.65,21.75,21.18750,0,41.044633,28.892364
25,2020-05-28 05:00:00,ESENLER,0,13.640,15.89,14.70317,80.90,92.00,86.46500,0.000,...,0.00000,14.0,18.8,16.13167,13.64,17.47,15.96500,0,41.044633,28.892364
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
738718,2020-11-20 21:00:00,DURUSU,0,10.440,11.36,10.89172,58.96,75.26,68.03552,3.019,...,0.00000,9.9,10.4,10.22241,8.07,10.34,9.22966,2,41.274381,28.661106
738720,2020-11-22 02:00:00,DURUSU,0,9.380,10.06,9.73895,80.70,84.40,82.82632,4.876,...,0.00614,8.7,8.7,8.70000,6.24,8.28,7.31737,2,41.274381,28.661106
738780,2020-11-26 19:00:00,DURUSU,0,7.541,9.65,9.17069,77.99,88.10,80.84644,0.339,...,0.00000,7.5,8.2,7.92881,7.22,11.69,9.73898,2,41.274381,28.661106
738787,2020-11-24 15:00:00,ZINCIRLIKUYU,0,10.970,11.38,11.16600,63.71,66.30,64.81883,0.850,...,0.00000,13.1,13.7,13.41667,10.18,12.37,11.32833,1,41.066714,29.013019
738802,2020-11-14 11:00:00,PENDIK,0,12.800,13.41,13.18850,80.40,83.60,81.69000,0.000,...,0.00133,14.4,14.9,14.57333,12.80,14.80,13.21383,4,40.889519,29.237103

In [15]:
traffic_data = pd.concat([pd.read_csv(i) for i in glob.glob("../trafik_yogunlugu/*")]).reset_index(drop=True)

In [16]:
from datetime import datetime

traffic_data['DATE_TIME'] = pd.to_datetime(traffic_data['DATE_TIME'])

traffic_data = traffic_data[traffic_data['DATE_TIME'].dt.strftime('%H:%M:%S').between('06:00:00','24:00:00')]

In [17]:
import random
traffic_data = traffic_data.sample(n=1000000 ,replace=True,random_state= 30)

In [18]:
traffic_data

,DATE_TIME,LONGITUDE,LATITUDE,GEOHASH,MINIMUM_SPEED,MAXIMUM_SPEED,AVERAGE_SPEED,NUMBER_OF_VEHICLES
18333454,2021-04-18 21:00:00,28.679810,41.053162,sxk3s9,11,133,66,102
15202541,2020-08-17 13:00:00,28.822632,40.959778,sxk3pb,6,50,21,37
9592031,2020-03-09 22:00:00,29.130249,41.014709,sxk9qf,6,58,26,45
17788251,2021-04-15 14:00:00,29.097290,41.031189,sxk9qj,2,104,33,245
15077514,2020-11-02 18:00:00,28.789673,40.987244,sxk3pj,6,103,36,351
...,...,...,...,...,...,...,...,...
4224569,2020-06-21 11:00:00,29.218140,40.943298,sxkbbv,13,120,70,75
886654,2020-04-22 21:00:00,28.756714,41.239929,sxk6w7,57,91,78,27
13378987,2021-03-14 13:00:00,28.789673,40.970764,sxk3p4,7,68,41,14
13998406,2020-11-16 19:00:00,28.943481,41.113586,sxk9fs,46,106,72,138
18489732,2021-04-13 11:00:00,28.679810,40.970764,sxk3hd,11,48,31,15

In [19]:
traffic_data = traffic_data.sort_values(by=['DATE_TIME'])

In [20]:
traffic_data

,DATE_TIME,LONGITUDE,LATITUDE,GEOHASH,MINIMUM_SPEED,MAXIMUM_SPEED,AVERAGE_SPEED,NUMBER_OF_VEHICLES
6900177,2020-01-01 06:00:00,28.932495,40.998230,sxk94r,7,101,46,21
7210593,2020-01-01 06:00:00,28.932495,41.042175,sxk96r,6,80,45,36
6986243,2020-01-01 06:00:00,29.262085,41.163025,sxkf1v,36,113,84,21
6605494,2020-01-01 06:00:00,28.877563,40.976257,sxk915,8,98,47,18
6445961,2020-01-01 06:00:00,28.690796,40.998230,sxk3hz,41,104,65,67
...,...,...,...,...,...,...,...,...
7686421,2021-05-03 22:00:00,28.723755,41.195984,sxk6me,11,62,35,24
7725721,2021-05-03 22:00:00,29.338989,40.987244,sxkc5t,52,120,79,28
7663864,2021-05-03 22:00:00,28.833618,41.053162,sxk981,3,74,33,54
7694677,2021-05-03 22:00:00,28.580933,41.108093,sxk3f7,47,123,86,76
7642270,2021-05-03 22:00:00,29.349976,40.822449,sxkb5z,6,148,66,182

In [21]:
traffic_data['HOUR'] = traffic_data['DATE_TIME'].dt.strftime('%H')

traffic_data['AY'] = traffic_data['DATE_TIME'].dt.strftime('%m')

traffic_data['GUN'] = traffic_data['DATE_TIME'].dt.strftime('%d')

In [22]:
traffic_data['WEEKDAY'] = traffic_data['DATE_TIME'].dt.day_name()

traffic_data['MONTH'] = traffic_data['DATE_TIME'].dt.month_name()

In [23]:
traffic_data

,DATE_TIME,LONGITUDE,LATITUDE,GEOHASH,MINIMUM_SPEED,MAXIMUM_SPEED,AVERAGE_SPEED,NUMBER_OF_VEHICLES,HOUR,AY,GUN,WEEKDAY,MONTH
6900177,2020-01-01 06:00:00,28.932495,40.998230,sxk94r,7,101,46,21,06,01,01,Wednesday,January
7210593,2020-01-01 06:00:00,28.932495,41.042175,sxk96r,6,80,45,36,06,01,01,Wednesday,January
6986243,2020-01-01 06:00:00,29.262085,41.163025,sxkf1v,36,113,84,21,06,01,01,Wednesday,January
6605494,2020-01-01 06:00:00,28.877563,40.976257,sxk915,8,98,47,18,06,01,01,Wednesday,January
6445961,2020-01-01 06:00:00,28.690796,40.998230,sxk3hz,41,104,65,67,06,01,01,Wednesday,January
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7686421,2021-05-03 22:00:00,28.723755,41.195984,sxk6me,11,62,35,24,22,05,03,Monday,May
7725721,2021-05-03 22:00:00,29.338989,40.987244,sxkc5t,52,120,79,28,22,05,03,Monday,May
7663864,2021-05-03 22:00:00,28.833618,41.053162,sxk981,3,74,33,54,22,05,03,Monday,May
7694677,2021-05-03 22:00:00,28.580933,41.108093,sxk3f7,47,123,86,76,22,05,03,Monday,May
7642270,2021-05-03 22:00:00,29.349976,40.822449,sxkb5z,6,148,66,182,22,05,03,Monday,May

In [24]:
import numpy as np
one_hot_m = pd.get_dummies(traffic_data['MONTH'])
one_hot_d = pd.get_dummies(traffic_data['WEEKDAY'])
one_hot_h = pd.get_dummies(traffic_data['HOUR'])


traffic_data = traffic_data.join(one_hot_d ,lsuffix=None, rsuffix=None)

traffic_data = traffic_data.join(one_hot_m , lsuffix='_monthl' , rsuffix='_monthr')

traffic_data = traffic_data.join(one_hot_h ,lsuffix='_hourl', rsuffix='_hour')

In [25]:
traffic_data.columns

Index(['DATE_TIME', 'LONGITUDE', 'LATITUDE', 'GEOHASH', 'MINIMUM_SPEED',
       'MAXIMUM_SPEED', 'AVERAGE_SPEED', 'NUMBER_OF_VEHICLES', 'HOUR', 'AY',
       'GUN', 'WEEKDAY', 'MONTH', 'Friday', 'Monday', 'Saturday', 'Sunday',
       'Thursday', 'Tuesday', 'Wednesday', 'April', 'August', 'December',
       'February', 'January', 'July', 'June', 'March', 'May', 'November',
       'October', 'September', '06', '07', '08', '09', '10', '11', '12', '13',
       '14', '15', '16', '17', '18', '19', '20', '21', '22', '23'],
      dtype='object')

In [26]:
traffic_data.drop(columns=['GUN','AY','HOUR','WEEKDAY','MONTH'],axis=1,inplace=True)

traffic_data.columns

Index(['DATE_TIME', 'LONGITUDE', 'LATITUDE', 'GEOHASH', 'MINIMUM_SPEED',
       'MAXIMUM_SPEED', 'AVERAGE_SPEED', 'NUMBER_OF_VEHICLES', 'Friday',
       'Monday', 'Saturday', 'Sunday', 'Thursday', 'Tuesday', 'Wednesday',
       'April', 'August', 'December', 'February', 'January', 'July', 'June',
       'March', 'May', 'November', 'October', 'September', '06', '07', '08',
       '09', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20',
       '21', '22', '23'],
      dtype='object')

In [27]:
traffic_data = traffic_data.reset_index(drop=True)

In [28]:
traffic_data

,DATE_TIME,LONGITUDE,LATITUDE,GEOHASH,MINIMUM_SPEED,MAXIMUM_SPEED,AVERAGE_SPEED,NUMBER_OF_VEHICLES,Friday,Monday,...,14,15,16,17,18,19,20,21,22,23
0,2020-04-24 07:00:00,28.800659,41.058655,sxk3x6,7,69,36,44,1,0,...,0,0,0,0,0,0,0,0,0,0
1,2020-04-14 16:00:00,29.152222,40.948792,sxk8zq,7,108,45,36,0,0,...,0,0,1,0,0,0,0,0,0,0
2,2020-04-29 12:00:00,28.976440,41.075134,sxk9em,6,63,21,68,0,0,...,0,0,0,0,0,0,0,0,0,0
3,2020-04-01 07:00:00,29.020386,41.124573,sxk9uq,13,120,67,72,0,0,...,0,0,0,0,0,0,0,0,0,0
4,2020-04-23 12:00:00,28.998413,41.036682,sxk97y,9,65,34,16,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1440855,2020-09-12 12:00:00,27.998657,41.206970,sx7fmj,56,167,82,64,0,0,...,0,0,0,0,0,0,0,0,0,0
1440856,2020-09-10 07:00:00,29.086304,40.998230,sxk9jz,6,57,26,121,0,0,...,0,0,0,0,0,0,0,0,0,0
1440857,2020-09-29 08:00:00,28.482056,41.020203,sxk325,52,145,80,85,0,0,...,0,0,0,0,0,0,0,0,0,0
1440858,2020-09-29 08:00:00,28.987427,41.102600,sxk9gd,7,131,60,468,0,0,...,0,0,0,0,0,0,0,0,0,0
1440859,2020-09-30 13:00:00,29.031372,41.086121,sxk9sx,6,53,27,75,0,0,...,0,0,0,0,0,0,0,0,0,0

In [29]:
#def measure_distance(c1,c2):
 #   return geodesic(c1,(c2["latitude"],c2["longitude"])).miles

from functools import lru_cache

@lru_cache
def measure_distance(c1,c2):
    return geodesic(c1,c2).miles

In [30]:
temp = []
from geopy.distance import geodesic
    
merged_df = pd.DataFrame(columns=['DATE_TIME', 'LONGITUDE', 'LATITUDE', 'GEOHASH', 'MINIMUM_SPEED',
       'MAXIMUM_SPEED', 'AVERAGE_SPEED', 'NUMBER_OF_VEHICLES', 'Friday',
       'Monday', 'Saturday', 'Sunday', 'Thursday', 'Tuesday', 'Wednesday',
       'April', 'August', 'December', 'February', 'January', 'July', 'June',
       'March', 'May', 'November', 'October', 'September', '06', '07', '08',
       '09', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20',
       '21', '22', '23',
       'MINIMUM_TEMPERATURE', 'MAXIMUM_TEMPERATURE', 'AVERAGE_TEMPERATURE',
       'MINIMUM_HUMIDITY', 'MAXIMUM_HUMIDITY', 'AVERAGE_HUMIDITY',
       'MINIMUM_WIND', 'MAXIMUM_WIND', 'AVERAGE_WIND',
       'MINIMUM_DIRECTIONOFWIND', 'MAXIMUM_DIRECTIONOFWIND',
       'AVERAGE_DIRECTIONOFWIND', 'MINIMUM_PRECIPITATION',
       'MAXIMUM_PRECIPITATION', 'AVERAGE_PRECIPITATION',
       'MINIMUM_ROAD_TEMPERATURE', 'MAXIMUM_ROAD_TEMPERATURE',
       'AVERAGE_ROAD_TEMPERATURE', 'MINIMUM_FELT_TEMPERATURE',
       'MAXIMUM_FELT_TEMPERATURE', 'AVERAGE_FELT_TEMPERATURE', 'distance'])

def profile(func):
    from functools import wraps

    @wraps(func)
    def wrapper(*args, **kwargs):
        from line_profiler import LineProfiler
        prof = LineProfiler()
        try:
            return prof(func)(*args, **kwargs)
        finally:
            prof.print_stats()

    return wrapper
    
    
#@profile
def merge(traffic_data,weather_data,merged_df):
    liste = []
    for i in tqdm(range(len(traffic_data[:100]))):
        dt = traffic_data.DATE_TIME[i]
        c1 = (traffic_data.LATITUDE[i],traffic_data.LONGITUDE[i])
        temp_df = weather_data[weather_data.DATE_TIME==str(dt)].copy()
        if len(temp_df) != 0:
            temp_df.loc[:,"distance"] = temp_df.apply(lambda c2: measure_distance(c1,(c2["latitude"],c2["longitude"])),axis=1)

            temp_df = temp_df.drop(["latitude","longitude"],axis=1).select_dtypes("float")
            
        
            x = temp_df.loc[temp_df.distance.idxmin()]
            x.name = i
            
            #merged_df.loc[i] = pd.concat([traffic_data.iloc[i],x],axis=0)
            
            liste.append([traffic_data.iloc[i],x])
            
    return liste
        

output = merge(traffic_data,weather_data,merged_df)

100%|██████████| 100000/100000 [10:23<00:00, 160.47it/s]

In [31]:
a1 = pd.concat([i[1] for i in output],axis=1)
a2 = pd.concat([i[0] for i in output],axis=1)
merged_df = pd.concat([a2,a1]).transpose()

In [25]:
#import pickle

#with open('1m.pickle', 'wb') as handle:
#    pickle.dump(merged_df, handle, protocol=pickle.HIGHEST_PROTOCOL)

In [1]:
#import pickle 
#with open('1m.pickle', 'rb') as f:
#    merged_df = pickle.load(f)

In [32]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 95385 entries, 0 to 99999
Data columns (total 67 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   DATE_TIME                 95385 non-null  datetime64[ns]
 1   LONGITUDE                 95385 non-null  object
 2   LATITUDE                  95385 non-null  object
 3   GEOHASH                   95385 non-null  object
 4   MINIMUM_SPEED             95385 non-null  object
 5   MAXIMUM_SPEED             95385 non-null  object
 6   AVERAGE_SPEED             95385 non-null  object
 7   NUMBER_OF_VEHICLES        95385 non-null  object
 8   Friday                    95385 non-null  object
 9   Monday                    95385 non-null  object
 10  Saturday                  95385 non-null  object
 11  Sunday                    95385 non-null  object
 12  Thursday                  95385 non-null  object
 13  Tuesday                   95385 non-null  object
 14  Wednesday                 95385 non-null  object
 15  April                     95385 non-null  object
 16  August                    95385 non-null  object
 17  December                  95385 non-null  object
 18  February                  95385 non-null  object
 19  January                   95385 non-null  object
 20  July                      95385 non-null  object
 21  June                      95385 non-null  object
 22  March                     95385 non-null  object
 23  May                       95385 non-null  object
 24  November                  95385 non-null  object
 25  October                   95385 non-null  object
 26  September                 95385 non-null  object
 27  06                        95385 non-null  object
 28  07                        95385 non-null  object
 29  08                        95385 non-null  object
 30  09                        95385 non-null  object
 31  10                        95385 non-null  object
 32  11                        95385 non-null  object
 33  12                        95385 non-null  object
 34  13                        95385 non-null  object
 35  14                        95385 non-null  object
 36  15                        95385 non-null  object
 37  16                        95385 non-null  object
 38  17                        95385 non-null  object
 39  18                        95385 non-null  object
 40  19                        95385 non-null  object
 41  20                        95385 non-null  object
 42  21                        95385 non-null  object
 43  22                        95385 non-null  object
 44  23                        95385 non-null  object
 45  MINIMUM_TEMPERATURE       95385 non-null  object
 46  MAXIMUM_TEMPERATURE       95385 non-null  object
 47  AVERAGE_TEMPERATURE       95385 non-null  object
 48  MINIMUM_HUMIDITY          95385 non-null  object
 49  MAXIMUM_HUMIDITY          95385 non-null  object
 50  AVERAGE_HUMIDITY          95385 non-null  object
 51  MINIMUM_WIND              95385 non-null  object
 52  MAXIMUM_WIND              95385 non-null  object
 53  AVERAGE_WIND              95385 non-null  object
 54  MINIMUM_DIRECTIONOFWIND   95385 non-null  object
 55  MAXIMUM_DIRECTIONOFWIND   95385 non-null  object
 56  AVERAGE_DIRECTIONOFWIND   95385 non-null  object
 57  MINIMUM_PRECIPITATION     95385 non-null  object
 58  MAXIMUM_PRECIPITATION     95385 non-null  object
 59  AVERAGE_PRECIPITATION     95385 non-null  object
 60  MINIMUM_ROAD_TEMPERATURE  95385 non-null  object
 61  MAXIMUM_ROAD_TEMPERATURE  95385 non-null  object
 62  AVERAGE_ROAD_TEMPERATURE  95385 non-null  object
 63  MINIMUM_FELT_TEMPERATURE  95385 non-null  object
 64  MAXIMUM_FELT_TEMPERATURE  95385 non-null  object
 65  AVERAGE_FELT_TEMPERATURE  95385 non-null  object
 66  distance                  95385 non-null  object
dtypes: datetime64[ns](1), object(66)
memory usage: 49.5+ MB

####

In [33]:
merged_df = merged_df.sort_values(by=['DATE_TIME'])

In [34]:
merged_df.head(50)

,DATE_TIME,LONGITUDE,LATITUDE,GEOHASH,MINIMUM_SPEED,MAXIMUM_SPEED,AVERAGE_SPEED,NUMBER_OF_VEHICLES,Friday,Monday,...,MINIMUM_PRECIPITATION,MAXIMUM_PRECIPITATION,AVERAGE_PRECIPITATION,MINIMUM_ROAD_TEMPERATURE,MAXIMUM_ROAD_TEMPERATURE,AVERAGE_ROAD_TEMPERATURE,MINIMUM_FELT_TEMPERATURE,MAXIMUM_FELT_TEMPERATURE,AVERAGE_FELT_TEMPERATURE,distance
36666,2020-04-01 06:00:00,29.09729,41.047668,sxk9w0,8,43,27,26,0,0,...,0.0,0.52,0.27644,7.1,8.1,7.53051,3.28,4.98,4.07119,4.5938
80734,2020-04-01 06:00:00,28.811646,41.135559,sxk6p8,17,120,77,84,0,0,...,0.0,0.0,0.0,12.5,12.5,12.5,6.16,8.53,7.19213,7.558321
70817,2020-04-01 06:00:00,28.624878,41.091614,sxk3g2,55,162,85,85,0,0,...,0.0,0.0,0.0,7.4,7.8,7.60167,2.13,4.24,3.03767,12.752984
59133,2020-04-01 06:00:00,28.789673,41.003723,sxk3r0,7,44,22,63,0,0,...,0.0,0.0,0.0,12.5,12.5,12.5,6.16,8.53,7.19213,6.063862
55369,2020-04-01 06:00:00,28.833618,41.130066,sxk9bp,7,116,63,74,0,0,...,0.0,0.0,0.0,12.5,12.5,12.5,6.16,8.53,7.19213,6.645544
26491,2020-04-01 06:00:00,28.624878,41.11908,sxk3gm,6,128,56,92,0,0,...,0.0,0.0,0.0,7.4,7.8,7.60167,2.13,4.24,3.03767,10.882104
7671,2020-04-01 06:00:00,29.130249,40.99823,sxk9nz,6,142,79,237,0,0,...,0.0,0.52,0.27644,7.1,8.1,7.53051,3.28,4.98,4.07119,7.736725
11112,2020-04-01 06:00:00,28.262329,41.075134,sxk1ej,9,119,66,41,0,0,...,0.0,0.0,0.0,7.4,7.8,7.60167,2.13,4.24,3.03767,24.92745
61504,2020-04-01 06:00:00,29.174194,41.020203,sxk9rg,7,99,49,118,0,0,...,0.0,0.52,0.27644,7.1,8.1,7.53051,3.28,4.98,4.07119,9.011493
72884,2020-04-01 06:00:00,28.493042,41.124573,sxk3bq,36,94,74,18,0,0,...,0.0,0.0,0.0,7.4,7.8,7.60167,2.13,4.24,3.03767,13.550096
61503,2020-04-01 06:00:00,29.174194,41.020203,sxk9rg,7,99,49,118,0,0,...,0.0,0.52,0.27644,7.1,8.1,7.53051,3.28,4.98,4.07119,9.011493
61502,2020-04-01 06:00:00,29.174194,41.020203,sxk9rg,7,99,49,118,0,0,...,0.0,0.52,0.27644,7.1,8.1,7.53051,3.28,4.98,4.07119,9.011493
10220,2020-04-01 06:00:00,28.295288,41.141052,sxk45c,31,135,82,25,0,0,...,0.0,0.0,0.0,7.4,7.8,7.60167,2.13,4.24,3.03767,21.168531
61501,2020-04-01 06:00:00,29.174194,41.020203,sxk9rg,7,99,49,118,0,0,...,0.0,0.52,0.27644,7.1,8.1,7.53051,3.28,4.98,4.07119,9.011493
61500,2020-04-01 06:00:00,29.174194,41.020203,sxk9rg,7,99,49,118,0,0,...,0.0,0.52,0.27644,7.1,8.1,7.53051,3.28,4.98,4.07119,9.011493
61499,2020-04-01 06:00:00,29.174194,41.020203,sxk9rg,7,99,49,118,0,0,...,0.0,0.52,0.27644,7.1,8.1,7.53051,3.28,4.98,4.07119,9.011493
68071,2020-04-01 06:00:00,28.899536,40.987244,sxk91t,7,42,22,20,0,0,...,0.0,0.0,0.0,12.5,12.5,12.5,6.16,8.53,7.19213,3.977929
33747,2020-04-01 06:00:00,29.229126,41.025696,sxkc3h,27,112,72,94,0,0,...,0.0,0.52,0.27644,7.1,8.1,7.53051,3.28,4.98,4.07119,11.639386
61828,2020-04-01 06:00:00,28.196411,41.11908,sxk1ct,61,152,86,70,0,0,...,0.0,0.0,0.0,7.4,7.8,7.60167,2.13,4.24,3.03767,26.486436
66138,2020-04-01 06:00:00,28.240356,41.086121,sxk1dx,11,81,50,15,0,0,...,0.0,0.0,0.0,7.4,7.8,7.60167,2.13,4.24,3.03767,25.494696
45083,2020-04-01 06:00:00,28.910522,41.091614,sxk9cb,6,145,62,430,0,0,...,0.0,0.0,0.0,7.7,9.0,8.2,5.62,7.92,6.91283,2.987505
58312,2020-04-01 06:00:00,29.09729,41.020203,sxk9q5,6,54,24,38,0,0,...,0.0,0.52,0.27644,7.1,8.1,7.53051,3.28,4.98,4.07119,5.448403
47201,2020-04-01 06:00:00,28.383179,41.075134,sxk1tv,64,138,85,61,0,0,...,0.0,0.0,0.0,7.4,7.8,7.60167,2.13,4.24,3.03767,19.97619
35015,2020-04-01 06:00:00,28.899536,41.036682,sxk93w,7,85,32,89,0,0,...,0.0,0.0,0.0,12.5,12.5,12.5,6.16,8.53,7.19213,0.664435
48678,2020-04-01 06:00:00,28.987427,41.080627,sxk9ew,6,48,25,43,0,0,...,0.0,0.52,0.27644,7.1,8.1,7.53051,3.28,4.98,4.07119,1.645602
29009,2020-04-01 06:00:00,29.262085,41.031189,sxkc3v,12,114,64,65,0,0,...,0.0,0.52,0.27644,7.1,8.1,7.53051,3.28,4.98,4.07119,13.240221
35065,2020-04-01 06:00:00,28.778687,41.217957,sxk6qz,40,110,76,22,0,0,...,0.0,0.0,0.0,7.4,7.8,7.60167,2.13,4.24,3.03767,7.257131
61498,2020-04-01 06:00:00,29.174194,41.020203,sxk9rg,7,99,49,118,0,0,...,0.0,0.52,0.27644,7.1,8.1,7.53051,3.28,4.98,4.07119,9.011493
80086,2020-04-01 06:00:00,28.778687,41.047668,sxk3wb,6,70,33,16,0,0,...,0.0,0.0,0.0,12.5,12.5,12.5,6.16,8.53,7.19213,5.942504
58163,2020-04-01 06:00:00,28.723755,40.992737,sxk3jw,7,93,45,49,0,0,...,0.0,0.0,0.0,12.5,12.5,12.5,6.16,8.53,7.19213,9.512123
32973,2020-04-01 06:00:00,28.800659,41.1026,sxk3z6,13,81,45,19,0,0,...,0.0,0.0,0.0,12.5,12.5,12.5,6.16,8.53,7.19213,6.239739
46404,2020-04-01 06:00:00,28.262329,41.146545,sxk454,72,99,86,15,0,0,...,0.0,0.0,0.0,7.4,7.8,7.60167,2.13,4.24,3.03767,22.576116
17179,2020-04-01 06:00:00,28.943481,41.014709,sxk96d,7,78,37,48,0,0,...,0.0,0.0,0.0,12.5,12.5,12.5,6.16,8.53,7.19213,3.376264
50848,2020-04-01 06:00:00,28.88855,41.064148,sxk997,8,123,58,139,0,0,...,0.0,0.0,0.0,12.5,12.5,12.5,6.16,8.53,7.19213,1.361291
3290,2020-04-01 06:00:00,29.273071,40.965271,sxkc41,6,155,74,279,0,0,...,0.0,0.52,0.27644,7.1,8.1,7.53051,3.28,4.98,4.07119,15.28871
80618,2020-04-01 06:00:00,29.207153,40.888367,sxkb8e,7,80,34,54,0,0,...,0.0,0.52,0.27644,7.1,8.1,7.53051,3.28,4.98,4.07119,15.954167
55614,2020-04-01 06:00:00,28.745728,41.190491,sxk6q4,7,73,33,33,0,0,...,0.0,0.0,0.0,7.4,7.8,7.60167,2.13,4.24,3.03767,7.276517
61497,2020-04-01 06:00:00,29.174194,41.020203,sxk9rg,7,99,49,118,0,0,...,0.0,0.52,0.27644,7.1,8.1,7.53051,3.28,4.98,4.07119,9.011493
61496,2020-04-01 06:00:00,29.174194,41.020203,sxk9rg,7,99,49,118,0,0,...,0.0,0.52,0.27644,7.1,8.1,7.53051,3.28,4.98,4.07119,9.011493
61495,2020-04-01 06:00:00,29.174194,41.020203,sxk9rg,7,99,49,118,0,0,...,0.0,0.52,0.27644,7.1,8.1,7.53051,3.28,4.98,4.07119,9.011493
70843,2020-04-01 06:00:00,29.21814,40.926819,sxkbbf,6,70,34,36,0,0,...,0.0,0.52,0.27644,7.1,8.1,7.53051,3.28,4.98,4.07119,14.428992
45977,2020-04-01 06:00:00,28.624878,41.003723,sxk372,6,72,35,39,0,0,...,0.0,0.0,0.0,12.5,12.5,12.5,6.16,8.53,7.19213,14.26104
35290,2020-04-01 06:00:00,28.690796,41.075134,sxk3sv,12,63,32,18,0,0,...,0.0,0.0,0.0,12.5,12.5,12.5,6.16,8.53,7.19213,10.736589
46065,2020-04-01 06:00:00,28.482056,41.135559,sxk600,69,125,92,12,0,0,...,0.0,0.0,0.0,7.4,7.8,7.60167,2.13,4.24,3.03767,13.373482
21935,2020-04-01 06:00:00,28.196411,41.080627,sxk19w,36,138,76,34,0,0,...,0.0,0.0,0.0,7.4,7.8,7.60167,2.13,4.24,3.03767,27.672898
42488,2020-04-01 06:00:00,29.119263,41.031189,sxk9qt,7,167,73,336,0,0,...,0.0,0.52,0.27644,7.1,8.1,7.53051,3.28,4.98,4.07119,6.067477
73604,2020-04-01 06:00:00,29.130249,40.926819,sxk8yf,6,73,31,48,0,0,...,0.0,0.52,0.27644,7.1,8.1,7.53051,3.28,4.98,4.07119,11.434823
80877,2020-04-01 06:00:00,29.371948,40.833435,sxkbk3,11,154,90,94,0,0,...,0.0,0.52,0.27644,7.1,8.1,7.53051,3.28,4.98,4.07119,24.733844
41630,2020-04-01 06:00:00,28.833618,40.965271,sxk901,8,103,50,23,0,0,...,0.0,0.0,0.0,12.5,12.5,12.5,6.16,8.53,7.19213,6.278719
64483,2020-04-01 06:00:00,28.910522,41.058655,sxk99f,6,70,26,152,0,0,...,0.0,0.0,0.0,12.5,12.5,12.5,6.16,8.53,7.19213,1.354984

In [35]:
import pandas as pd
import glob
metro_data = pd.concat([pd.read_csv(i) for i in glob.glob("../toplu_ulasım/*")]).reset_index(drop=True)

In [36]:
metro_data

,DATE_TIME,TRANSPORT_TYPE_ID,TRANSPORT_TYPE_DESC,LINE,TRANSFER_TYPE_ID,TRANSFER_TYPE,NUMBER_OF_PASSENGER,NUMBER_OF_PASSAGE
0,2021-01-11 11:00:00,2.0,RAY,KABATAŞ-MAHMUTBEY,2,AKTARMA,541,545
1,2021-01-18 06:00:00,1.0,KARAYOLU,ÖHO,2,AKTARMA,1834,1867
2,2021-01-01 17:00:00,1.0,KARAYOLU,İETT,2,NORMAL,7406,7868
3,2021-01-18 20:00:00,1.0,KARAYOLU,ÖHO,2,AKTARMA,7064,7199
4,2021-01-22 05:00:00,2.0,RAY,AKSARAY-HAVALİMANI,2,NORMAL,712,713
...,...,...,...,...,...,...,...,...
343633,2020-07-18 06:00:00,2.0,RAY,MARMARAY,2,NORMAL,4325,4405
343634,2020-07-18 13:00:00,2.0,RAY,MARMARAY,2,AKTARMA,3238,3255
343635,2020-07-31 17:00:00,2.0,RAY,KADIKÖY-KARTAL METROSU,2,AKTARMA,1585,1595
343636,2020-07-28 14:00:00,3.0,DENİZ,ŞEHİR HATLARI,2,AKTARMA,1344,1349
343637,2020-07-05 23:00:00,2.0,RAY,LEVENT - RUMELİ HİSARÜSTÜ,2,AKTARMA,20,20

In [37]:
DATA_BOLGE = {"KABATAŞ-MAHMUTBEY":{'M1':0,'M2':40,'M3':60},
    "ÖHO":{'M1':33.3,'M2':33.3,'M3':33.3},
    "İETT":{'M1':33.3,'M2':33.3,'M3':33.3},
    "AKSARAY-HAVALİMANI":{'M1':0,'M2':0,'M3':100},
    "MOTOR TEKNE":{'M1':50,'M2':50,'M3':0},
    "KADIKÖY-MODA":{'M1':100,'M2':0,'M3':0},
    "EDİRNEKAPI-SULTANÇİFTLİĞİ":{'M1':0,'M2':0,'M3':100},
    "İETT NOSTALJİK TRAMVAY":{'M1':0,'M2':100,'M3':0},
    "KADIKÖY-KARTAL METROSU":{'M1':100,'M2':0,'M3':0},
    "KADIKÖY-MODA":{'M1':100,'M2':0,'M3':0},
    "TELEFERİK MAÇKA - TAŞKIŞLA":{'M1':0,'M2':100,'M3':0},
    "İETT TÜNEL":{'M1':0,'M2':100,'M3':0},
    "ÜSKÜDAR ÇEKMEKÖY METROSU":{'M1':100,'M2':0,'M3':0},
    "T5 EMİNÖNÜ-ALİBEYKÖY":{'M1':0,'M2':100,'M3':0},
    "MARMARAY":{'M1':50,'M2':20,'M3':30},
    "KİRAZLI-OLİMPİYATKÖY":{'M1':0,'M2':0,'M3':100},
    "ŞEHİR HATLARI":{'M1':33.3,'M2':33.3,'M3':33.3},
    "TAKSİM-KABATAŞ FUNİKULERİ":{'M1':0,'M2':100,'M3':0},
    "KABATAŞ-BAĞCILAR":{'M1':0,'M2':40,'M3':60},
    "METROBÜS":{'M1':20,'M2':30,'M3':50},
    "TAKSİM-4.LEVENT":{'M1':0,'M2':100,'M3':0},
    "TELEFERİK EYÜP PİYERLOTİ":{'M1':0,'M2':100,'M3':0},
    "LEVENT - RUMELİ HİSARÜSTÜ":{'M1':0,'M2':100,'M3':0}}

df_terr= pd.DataFrame(DATA_BOLGE.values())

In [38]:
d = pd.DataFrame(DATA_BOLGE)
d2 = d.from_dict(DATA_BOLGE, orient='index')

d2['LINE'] = d2.index


metro_area_data = pd.merge(metro_data, d2 ,on="LINE")

In [39]:
metro_area_data

,DATE_TIME,TRANSPORT_TYPE_ID,TRANSPORT_TYPE_DESC,LINE,TRANSFER_TYPE_ID,TRANSFER_TYPE,NUMBER_OF_PASSENGER,NUMBER_OF_PASSAGE,M1,M2,M3
0,2021-01-11 11:00:00,2.0,RAY,KABATAŞ-MAHMUTBEY,2,AKTARMA,541,545,0.0,40.0,60.0
1,2021-01-11 13:00:00,2.0,RAY,KABATAŞ-MAHMUTBEY,2,NORMAL,2246,2382,0.0,40.0,60.0
2,2021-01-11 19:00:00,2.0,RAY,KABATAŞ-MAHMUTBEY,2,AKTARMA,1750,1759,0.0,40.0,60.0
3,2021-01-11 20:00:00,2.0,RAY,KABATAŞ-MAHMUTBEY,2,AKTARMA,1015,1015,0.0,40.0,60.0
4,2021-01-11 18:00:00,2.0,RAY,KABATAŞ-MAHMUTBEY,2,AKTARMA,2252,2257,0.0,40.0,60.0
...,...,...,...,...,...,...,...,...,...,...,...
343624,2020-07-05 15:00:00,2.0,RAY,LEVENT - RUMELİ HİSARÜSTÜ,2,NORMAL,107,110,0.0,100.0,0.0
343625,2020-07-09 22:00:00,2.0,RAY,LEVENT - RUMELİ HİSARÜSTÜ,2,NORMAL,118,121,0.0,100.0,0.0
343626,2020-07-09 14:00:00,2.0,RAY,LEVENT - RUMELİ HİSARÜSTÜ,2,AKTARMA,115,119,0.0,100.0,0.0
343627,2020-07-09 15:00:00,2.0,RAY,LEVENT - RUMELİ HİSARÜSTÜ,2,AKTARMA,114,116,0.0,100.0,0.0
343628,2020-07-05 23:00:00,2.0,RAY,LEVENT - RUMELİ HİSARÜSTÜ,2,AKTARMA,20,20,0.0,100.0,0.0

In [40]:
metro_area_data.drop(columns=['TRANSPORT_TYPE_ID','TRANSPORT_TYPE_DESC','TRANSFER_TYPE_ID','TRANSFER_TYPE'])

,DATE_TIME,LINE,NUMBER_OF_PASSENGER,NUMBER_OF_PASSAGE,M1,M2,M3
0,2021-01-11 11:00:00,KABATAŞ-MAHMUTBEY,541,545,0.0,40.0,60.0
1,2021-01-11 13:00:00,KABATAŞ-MAHMUTBEY,2246,2382,0.0,40.0,60.0
2,2021-01-11 19:00:00,KABATAŞ-MAHMUTBEY,1750,1759,0.0,40.0,60.0
3,2021-01-11 20:00:00,KABATAŞ-MAHMUTBEY,1015,1015,0.0,40.0,60.0
4,2021-01-11 18:00:00,KABATAŞ-MAHMUTBEY,2252,2257,0.0,40.0,60.0
...,...,...,...,...,...,...,...
343624,2020-07-05 15:00:00,LEVENT - RUMELİ HİSARÜSTÜ,107,110,0.0,100.0,0.0
343625,2020-07-09 22:00:00,LEVENT - RUMELİ HİSARÜSTÜ,118,121,0.0,100.0,0.0
343626,2020-07-09 14:00:00,LEVENT - RUMELİ HİSARÜSTÜ,115,119,0.0,100.0,0.0
343627,2020-07-09 15:00:00,LEVENT - RUMELİ HİSARÜSTÜ,114,116,0.0,100.0,0.0
343628,2020-07-05 23:00:00,LEVENT - RUMELİ HİSARÜSTÜ,20,20,0.0,100.0,0.0

In [42]:
merged_df['YAGIS_SİDDETİ'] = pd.cut(merged_df['AVERAGE_PRECIPITATION'],bins=[0, 5, 15, 30],
                                             include_lowest = True,
                                             labels=['YAGISSIZ','HAFİF YAGIS','SİDDETLİ YAGIS'])



merged_df['SICAKLIK'] = pd.cut(merged_df['AVERAGE_TEMPERATURE'],bins=[4.09867,10, 16, 27.01106],
                                             include_lowest = True,
                                             labels=['SOGUK','ILIK','SICAK'])



merged_df['RUZGAR'] = pd.cut(merged_df['AVERAGE_HUMIDITY'],bins=[20.43685,40, 60, 100.0],
                                             include_lowest = True,
                                             labels=['RUZGARSIZ','RUZGARLI','AŞIRI RUZGARLI'])


merged_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 95385 entries, 36666 to 95923
Data columns (total 70 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   DATE_TIME                 95385 non-null  datetime64[ns]
 1   LONGITUDE                 95385 non-null  object
 2   LATITUDE                  95385 non-null  object
 3   GEOHASH                   95385 non-null  object
 4   MINIMUM_SPEED             95385 non-null  object
 5   MAXIMUM_SPEED             95385 non-null  object
 6   AVERAGE_SPEED             95385 non-null  object
 7   NUMBER_OF_VEHICLES        95385 non-null  object
 8   Friday                    95385 non-null  object
 9   Monday                    95385 non-null  object
 10  Saturday                  95385 non-null  object
 11  Sunday                    95385 non-null  object
 12  Thursday                  95385 non-null  object
 13  Tuesday                   95385 non-null  object
 14  Wednesday                 95385 non-null  object
 15  April                     95385 non-null  object
 16  August                    95385 non-null  object
 17  December                  95385 non-null  object
 18  February                  95385 non-null  object
 19  January                   95385 non-null  object
 20  July                      95385 non-null  object
 21  June                      95385 non-null  object
 22  March                     95385 non-null  object
 23  May                       95385 non-null  object
 24  November                  95385 non-null  object
 25  October                   95385 non-null  object
 26  September                 95385 non-null  object
 27  06                        95385 non-null  object
 28  07                        95385 non-null  object
 29  08                        95385 non-null  object
 30  09                        95385 non-null  object
 31  10                        95385 non-null  object
 32  11                        95385 non-null  object
 33  12                        95385 non-null  object
 34  13                        95385 non-null  object
 35  14                        95385 non-null  object
 36  15                        95385 non-null  object
 37  16                        95385 non-null  object
 38  17                        95385 non-null  object
 39  18                        95385 non-null  object
 40  19                        95385 non-null  object
 41  20                        95385 non-null  object
 42  21                        95385 non-null  object
 43  22                        95385 non-null  object
 44  23                        95385 non-null  object
 45  MINIMUM_TEMPERATURE       95385 non-null  object
 46  MAXIMUM_TEMPERATURE       95385 non-null  object
 47  AVERAGE_TEMPERATURE       95385 non-null  object
 48  MINIMUM_HUMIDITY          95385 non-null  object
 49  MAXIMUM_HUMIDITY          95385 non-null  object
 50  AVERAGE_HUMIDITY          95385 non-null  object
 51  MINIMUM_WIND              95385 non-null  object
 52  MAXIMUM_WIND              95385 non-null  object
 53  AVERAGE_WIND              95385 non-null  object
 54  MINIMUM_DIRECTIONOFWIND   95385 non-null  object
 55  MAXIMUM_DIRECTIONOFWIND   95385 non-null  object
 56  AVERAGE_DIRECTIONOFWIND   95385 non-null  object
 57  MINIMUM_PRECIPITATION     95385 non-null  object
 58  MAXIMUM_PRECIPITATION     95385 non-null  object
 59  AVERAGE_PRECIPITATION     95385 non-null  object
 60  MINIMUM_ROAD_TEMPERATURE  95385 non-null  object
 61  MAXIMUM_ROAD_TEMPERATURE  95385 non-null  object
 62  AVERAGE_ROAD_TEMPERATURE  95385 non-null  object
 63  MINIMUM_FELT_TEMPERATURE  95385 non-null  object
 64  MAXIMUM_FELT_TEMPERATURE  95385 non-null  object
 65  AVERAGE_FELT_TEMPERATURE  95385 non-null  object
 66  distance                  95385 non-null  object
 67  YAGIS_SİDDETİ             86868 non-null  category
 68  SICAKLIK                  90175 non-null  category
 69  RUZGAR                    95225 non-null  category
dtypes: category(3), datetime64[ns](1), object(66)
memory usage: 49.8+ MB

In [43]:

metro_area_data['DATE_TIME'] = metro_area_data['DATE_TIME'].astype('datetime64[ns]')

In [44]:
metro_area_data =metro_area_data.sort_values(by=['DATE_TIME'])

In [14]:
metro_area_data.head(50)

,DATE_TIME,TRANSPORT_TYPE_ID,TRANSPORT_TYPE_DESC,LINE,TRANSFER_TYPE_ID,TRANSFER_TYPE,NUMBER_OF_PASSENGER,NUMBER_OF_PASSAGE,M1,M2,M3
236166,2020-01-01 00:00:00,3.0,DENİZ,ŞEHİR HATLARI,2,AKTARMA,59,59,33.3,33.3,33.3
216836,2020-01-01 00:00:00,2.0,RAY,KİRAZLI-OLİMPİYATKÖY,2,AKTARMA,10,10,0.0,0.0,100.0
31118,2020-01-01 00:00:00,1.0,KARAYOLU,İETT,2,NORMAL,1426,1657,33.3,33.3,33.3
235985,2020-01-01 00:00:00,3.0,DENİZ,ŞEHİR HATLARI,2,NORMAL,431,550,33.3,33.3,33.3
271023,2020-01-01 00:00:00,2.0,RAY,KABATAŞ-BAĞCILAR,2,NORMAL,4310,6396,0.0,40.0,60.0
271253,2020-01-01 00:00:00,2.0,RAY,KABATAŞ-BAĞCILAR,2,AKTARMA,1586,1608,0.0,40.0,60.0
30907,2020-01-01 00:00:00,1.0,KARAYOLU,İETT,2,AKTARMA,124,124,33.3,33.3,33.3
52209,2020-01-01 00:00:00,2.0,RAY,AKSARAY-HAVALİMANI,2,AKTARMA,1376,1387,0.0,0.0,100.0
9936,2020-01-01 00:00:00,1.0,KARAYOLU,ÖHO,2,NORMAL,4770,6085,33.3,33.3,33.3
9964,2020-01-01 00:00:00,1.0,KARAYOLU,ÖHO,2,AKTARMA,497,499,33.3,33.3,33.3
327595,2020-01-01 00:00:00,2.0,RAY,LEVENT - RUMELİ HİSARÜSTÜ,2,AKTARMA,34,34,0.0,100.0,0.0
174843,2020-01-01 00:00:00,2.0,RAY,ÜSKÜDAR ÇEKMEKÖY METROSU,2,AKTARMA,585,589,100.0,0.0,0.0
327312,2020-01-01 00:00:00,2.0,RAY,LEVENT - RUMELİ HİSARÜSTÜ,2,NORMAL,163,173,0.0,100.0,0.0
73562,2020-01-01 00:00:00,3.0,DENİZ,MOTOR TEKNE,2,NORMAL,1393,1678,50.0,50.0,0.0
303175,2020-01-01 00:00:00,2.0,RAY,TAKSİM-4.LEVENT,2,AKTARMA,2189,2218,0.0,100.0,0.0
216153,2020-01-01 00:00:00,2.0,RAY,KİRAZLI-OLİMPİYATKÖY,2,NORMAL,137,171,0.0,0.0,100.0
256471,2020-01-01 00:00:00,2.0,RAY,TAKSİM-KABATAŞ FUNİKULERİ,2,NORMAL,694,1079,0.0,100.0,0.0
93548,2020-01-01 00:00:00,2.0,RAY,EDİRNEKAPI-SULTANÇİFTLİĞİ,2,AKTARMA,218,220,0.0,0.0,100.0
124779,2020-01-01 00:00:00,2.0,RAY,KADIKÖY-KARTAL METROSU,2,AKTARMA,677,686,100.0,0.0,0.0
74137,2020-01-01 00:00:00,3.0,DENİZ,MOTOR TEKNE,2,AKTARMA,331,341,50.0,50.0,0.0
94138,2020-01-01 00:00:00,2.0,RAY,EDİRNEKAPI-SULTANÇİFTLİĞİ,2,NORMAL,793,939,0.0,0.0,100.0
290455,2020-01-01 00:00:00,1.0,KARAYOLU,METROBÜS,2,NORMAL,8576,10017,20.0,30.0,50.0
303032,2020-01-01 00:00:00,2.0,RAY,TAKSİM-4.LEVENT,2,NORMAL,8119,10965,0.0,100.0,0.0
53006,2020-01-01 00:00:00,2.0,RAY,AKSARAY-HAVALİMANI,2,NORMAL,2936,3662,0.0,0.0,100.0
175263,2020-01-01 00:00:00,2.0,RAY,ÜSKÜDAR ÇEKMEKÖY METROSU,2,NORMAL,1901,2244,100.0,0.0,0.0
199979,2020-01-01 00:00:00,2.0,RAY,MARMARAY,2,NORMAL,3146,3872,50.0,20.0,30.0
124596,2020-01-01 00:00:00,2.0,RAY,KADIKÖY-KARTAL METROSU,2,NORMAL,2634,3127,100.0,0.0,0.0
256066,2020-01-01 00:00:00,2.0,RAY,TAKSİM-KABATAŞ FUNİKULERİ,2,AKTARMA,277,284,0.0,100.0,0.0
255963,2020-01-01 01:00:00,2.0,RAY,TAKSİM-KABATAŞ FUNİKULERİ,2,AKTARMA,117,120,0.0,100.0,0.0
30902,2020-01-01 01:00:00,1.0,KARAYOLU,İETT,2,AKTARMA,72,72,33.3,33.3,33.3
216817,2020-01-01 01:00:00,2.0,RAY,KİRAZLI-OLİMPİYATKÖY,2,AKTARMA,3,3,0.0,0.0,100.0
10719,2020-01-01 01:00:00,1.0,KARAYOLU,ÖHO,2,NORMAL,1055,1477,33.3,33.3,33.3
73565,2020-01-01 01:00:00,3.0,DENİZ,MOTOR TEKNE,2,AKTARMA,111,112,50.0,50.0,0.0
124958,2020-01-01 01:00:00,2.0,RAY,KADIKÖY-KARTAL METROSU,2,NORMAL,2647,3201,100.0,0.0,0.0
53414,2020-01-01 01:00:00,2.0,RAY,AKSARAY-HAVALİMANI,2,NORMAL,2582,3246,0.0,0.0,100.0
174991,2020-01-01 01:00:00,2.0,RAY,ÜSKÜDAR ÇEKMEKÖY METROSU,2,AKTARMA,552,556,100.0,0.0,0.0
271689,2020-01-01 01:00:00,2.0,RAY,KABATAŞ-BAĞCILAR,2,AKTARMA,717,738,0.0,40.0,60.0
303363,2020-01-01 01:00:00,2.0,RAY,TAKSİM-4.LEVENT,2,AKTARMA,1460,1483,0.0,100.0,0.0
270777,2020-01-01 01:00:00,2.0,RAY,KABATAŞ-BAĞCILAR,2,NORMAL,3952,6014,0.0,40.0,60.0
236023,2020-01-01 01:00:00,3.0,DENİZ,ŞEHİR HATLARI,2,NORMAL,76,92,33.3,33.3,33.3
327818,2020-01-01 01:00:00,2.0,RAY,LEVENT - RUMELİ HİSARÜSTÜ,2,NORMAL,167,181,0.0,100.0,0.0
94372,2020-01-01 01:00:00,2.0,RAY,EDİRNEKAPI-SULTANÇİFTLİĞİ,2,NORMAL,505,594,0.0,0.0,100.0
290069,2020-01-01 01:00:00,1.0,KARAYOLU,METROBÜS,2,NORMAL,9497,11493,20.0,30.0,50.0
302666,2020-01-01 01:00:00,2.0,RAY,TAKSİM-4.LEVENT,2,NORMAL,7307,9601,0.0,100.0,0.0
255954,2020-01-01 01:00:00,2.0,RAY,TAKSİM-KABATAŞ FUNİKULERİ,2,NORMAL,599,876,0.0,100.0,0.0
199666,2020-01-01 01:00:00,2.0,RAY,MARMARAY,2,NORMAL,2779,3382,50.0,20.0,30.0
74096,2020-01-01 01:00:00,3.0,DENİZ,MOTOR TEKNE,2,NORMAL,1276,1594,50.0,50.0,0.0
94723,2020-01-01 01:00:00,2.0,RAY,EDİRNEKAPI-SULTANÇİFTLİĞİ,2,AKTARMA,264,265,0.0,0.0,100.0
124459,2020-01-01 01:00:00,2.0,RAY,KADIKÖY-KARTAL METROSU,2,AKTARMA,669,676,100.0,0.0,0.0
237047,2020-01-01 01:00:00,3.0,DENİZ,ŞEHİR HATLARI,2,AKTARMA,1,1,33.3,33.3,33.3

In [45]:
data_ıst= pd.merge(merged_df,metro_area_data ,on="DATE_TIME")

In [28]:
data_ıst.columns

Index(['DATE_TIME', 'LONGITUDE', 'LATITUDE', 'GEOHASH', 'MINIMUM_SPEED',
       'MAXIMUM_SPEED', 'AVERAGE_SPEED', 'NUMBER_OF_VEHICLES', 'Friday',
       'Monday', 'Saturday', 'Sunday', 'Thursday', 'Tuesday', 'Wednesday',
       'April', 'August', 'December', 'February', 'January', 'July', 'June',
       'March', 'May', 'November', 'October', 'September', '06', '07', '08',
       '09', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20',
       '21', '22', '23', 'MINIMUM_TEMPERATURE', 'MAXIMUM_TEMPERATURE',
       'AVERAGE_TEMPERATURE', 'MINIMUM_HUMIDITY', 'MAXIMUM_HUMIDITY',
       'AVERAGE_HUMIDITY', 'MINIMUM_WIND', 'MAXIMUM_WIND', 'AVERAGE_WIND',
       'MINIMUM_DIRECTIONOFWIND', 'MAXIMUM_DIRECTIONOFWIND',
       'AVERAGE_DIRECTIONOFWIND', 'MINIMUM_PRECIPITATION',
       'MAXIMUM_PRECIPITATION', 'AVERAGE_PRECIPITATION',
       'MINIMUM_ROAD_TEMPERATURE', 'MAXIMUM_ROAD_TEMPERATURE',
       'AVERAGE_ROAD_TEMPERATURE', 'MINIMUM_FELT_TEMPERATURE',
       'MAXIMUM_FELT_TEMPERATURE', 'AVERAGE_FELT_TEMPERATURE', 'distance',
       'YAGIS_SİDDETİ', 'SICAKLIK', 'RUZGAR', 'TRANSPORT_TYPE_ID',
       'TRANSPORT_TYPE_DESC', 'LINE', 'TRANSFER_TYPE_ID', 'TRANSFER_TYPE',
       'NUMBER_OF_PASSENGER', 'NUMBER_OF_PASSAGE', 'M1', 'M2', 'M3'],
      dtype='object')

In [50]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 175908 entries, 61491 to 147378
Data columns (total 70 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   DATE_TIME                 175908 non-null  datetime64[ns]
 1   LONGITUDE                 175908 non-null  object
 2   LATITUDE                  175908 non-null  object
 3   GEOHASH                   175908 non-null  object
 4   MINIMUM_SPEED             175908 non-null  object
 5   MAXIMUM_SPEED             175908 non-null  object
 6   AVERAGE_SPEED             175908 non-null  object
 7   NUMBER_OF_VEHICLES        175908 non-null  object
 8   Friday                    175908 non-null  object
 9   Monday                    175908 non-null  object
 10  Saturday                  175908 non-null  object
 11  Sunday                    175908 non-null  object
 12  Thursday                  175908 non-null  object
 13  Tuesday                   175908 non-null  object
 14  Wednesday                 175908 non-null  object
 15  April                     175908 non-null  object
 16  August                    175908 non-null  object
 17  December                  175908 non-null  object
 18  February                  175908 non-null  object
 19  January                   175908 non-null  object
 20  July                      175908 non-null  object
 21  June                      175908 non-null  object
 22  March                     175908 non-null  object
 23  May                       175908 non-null  object
 24  November                  175908 non-null  object
 25  October                   175908 non-null  object
 26  September                 175908 non-null  object
 27  06                        175908 non-null  object
 28  07                        175908 non-null  object
 29  08                        175908 non-null  object
 30  09                        175908 non-null  object
 31  10                        175908 non-null  object
 32  11                        175908 non-null  object
 33  12                        175908 non-null  object
 34  13                        175908 non-null  object
 35  14                        175908 non-null  object
 36  15                        175908 non-null  object
 37  16                        175908 non-null  object
 38  17                        175908 non-null  object
 39  18                        175908 non-null  object
 40  19                        175908 non-null  object
 41  20                        175908 non-null  object
 42  21                        175908 non-null  object
 43  22                        175908 non-null  object
 44  23                        175908 non-null  object
 45  MINIMUM_TEMPERATURE       175908 non-null  object
 46  MAXIMUM_TEMPERATURE       175908 non-null  object
 47  AVERAGE_TEMPERATURE       175908 non-null  object
 48  MINIMUM_HUMIDITY          175908 non-null  object
 49  MAXIMUM_HUMIDITY          175908 non-null  object
 50  AVERAGE_HUMIDITY          175908 non-null  object
 51  MINIMUM_WIND              175908 non-null  object
 52  MAXIMUM_WIND              175908 non-null  object
 53  AVERAGE_WIND              175908 non-null  object
 54  MINIMUM_DIRECTIONOFWIND   175908 non-null  object
 55  MAXIMUM_DIRECTIONOFWIND   175908 non-null  object
 56  AVERAGE_DIRECTIONOFWIND   175908 non-null  object
 57  MINIMUM_PRECIPITATION     175908 non-null  object
 58  MAXIMUM_PRECIPITATION     175908 non-null  object
 59  AVERAGE_PRECIPITATION     175908 non-null  object
 60  MINIMUM_ROAD_TEMPERATURE  175908 non-null  object
 61  MAXIMUM_ROAD_TEMPERATURE  175908 non-null  object
 62  AVERAGE_ROAD_TEMPERATURE  175908 non-null  object
 63  MINIMUM_FELT_TEMPERATURE  175908 non-null  object
 64  MAXIMUM_FELT_TEMPERATURE  175908 non-null  object
 65  AVERAGE_FELT_TEMPERATURE  175908 non-null  object
 66  distance                  175908 non-null  object
 67  YAGIS_SİDDETİ             167307 non-null  category
 68  SICAKLIK                  151533 non-null  category
 69  RUZGAR                    175740 non-null  category
dtypes: category(3), datetime64[ns](1), object(66)
memory usage: 91.8+ MB

In [51]:
metro_area_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 343629 entries, 236166 to 271830
Data columns (total 11 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   DATE_TIME            343629 non-null  datetime64[ns]
 1   TRANSPORT_TYPE_ID    343629 non-null  float64
 2   TRANSPORT_TYPE_DESC  343629 non-null  object
 3   LINE                 343629 non-null  object
 4   TRANSFER_TYPE_ID     343629 non-null  int64
 5   TRANSFER_TYPE        343629 non-null  object
 6   NUMBER_OF_PASSENGER  343629 non-null  int64
 7   NUMBER_OF_PASSAGE    343629 non-null  int64
 8   M1                   343629 non-null  float64
 9   M2                   343629 non-null  float64
 10  M3                   343629 non-null  float64
dtypes: datetime64[ns](1), float64(4), int64(3), object(3)
memory usage: 31.5+ MB

In [17]:
data_ıst.head()

,DATE_TIME,LONGITUDE,LATITUDE,GEOHASH,MINIMUM_SPEED,MAXIMUM_SPEED,AVERAGE_SPEED,NUMBER_OF_VEHICLES,Friday,Monday,...,TRANSPORT_TYPE_ID,TRANSPORT_TYPE_DESC,LINE,TRANSFER_TYPE_ID,TRANSFER_TYPE,NUMBER_OF_PASSENGER,NUMBER_OF_PASSAGE,M1,M2,M3
0,2020-04-01 06:00:00,29.174194,41.020203,sxk9rg,7,99,49,118,0,0,...,3.0,DENİZ,MOTOR TEKNE,2,NORMAL,177,185,50.0,50.0,0.0
1,2020-04-01 06:00:00,29.174194,41.020203,sxk9rg,7,99,49,118,0,0,...,1.0,KARAYOLU,METROBÜS,2,NORMAL,5342,5382,20.0,30.0,50.0
2,2020-04-01 06:00:00,29.174194,41.020203,sxk9rg,7,99,49,118,0,0,...,2.0,RAY,ÜSKÜDAR ÇEKMEKÖY METROSU,2,AKTARMA,78,78,100.0,0.0,0.0
3,2020-04-01 06:00:00,29.174194,41.020203,sxk9rg,7,99,49,118,0,0,...,2.0,RAY,MARMARAY,2,AKTARMA,154,154,50.0,20.0,30.0
4,2020-04-01 06:00:00,29.174194,41.020203,sxk9rg,7,99,49,118,0,0,...,2.0,RAY,TAKSİM-4.LEVENT,2,NORMAL,1069,1076,0.0,100.0,0.0

In [46]:
data_ıst['M1_P'] = ( (data_ıst['NUMBER_OF_PASSENGER'] * 100) /data_ıst['NUMBER_OF_PASSAGE'] ) * data_ıst['M1']/100
data_ıst['M2_P'] = ( (data_ıst['NUMBER_OF_PASSENGER'] * 100) /data_ıst['NUMBER_OF_PASSAGE'] ) * data_ıst['M2']/100
data_ıst['M3_P'] = ( (data_ıst['NUMBER_OF_PASSENGER'] * 100) /data_ıst['NUMBER_OF_PASSAGE'] ) * data_ıst['M3']/100

In [30]:
data_ıst.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5542718 entries, 0 to 5542717
Data columns (total 83 columns):
 #   Column                    Dtype
---  ------                    -----
 0   DATE_TIME                 datetime64[ns]
 1   LONGITUDE                 object
 2   LATITUDE                  object
 3   GEOHASH                   object
 4   MINIMUM_SPEED             object
 5   MAXIMUM_SPEED             object
 6   AVERAGE_SPEED             object
 7   NUMBER_OF_VEHICLES        object
 8   Friday                    object
 9   Monday                    object
 10  Saturday                  object
 11  Sunday                    object
 12  Thursday                  object
 13  Tuesday                   object
 14  Wednesday                 object
 15  April                     object
 16  August                    object
 17  December                  object
 18  February                  object
 19  January                   object
 20  July                      object
 21  June                      object
 22  March                     object
 23  May                       object
 24  November                  object
 25  October                   object
 26  September                 object
 27  06                        object
 28  07                        object
 29  08                        object
 30  09                        object
 31  10                        object
 32  11                        object
 33  12                        object
 34  13                        object
 35  14                        object
 36  15                        object
 37  16                        object
 38  17                        object
 39  18                        object
 40  19                        object
 41  20                        object
 42  21                        object
 43  22                        object
 44  23                        object
 45  MINIMUM_TEMPERATURE       object
 46  MAXIMUM_TEMPERATURE       object
 47  AVERAGE_TEMPERATURE       object
 48  MINIMUM_HUMIDITY          object
 49  MAXIMUM_HUMIDITY          object
 50  AVERAGE_HUMIDITY          object
 51  MINIMUM_WIND              object
 52  MAXIMUM_WIND              object
 53  AVERAGE_WIND              object
 54  MINIMUM_DIRECTIONOFWIND   object
 55  MAXIMUM_DIRECTIONOFWIND   object
 56  AVERAGE_DIRECTIONOFWIND   object
 57  MINIMUM_PRECIPITATION     object
 58  MAXIMUM_PRECIPITATION     object
 59  AVERAGE_PRECIPITATION     object
 60  MINIMUM_ROAD_TEMPERATURE  object
 61  MAXIMUM_ROAD_TEMPERATURE  object
 62  AVERAGE_ROAD_TEMPERATURE  object
 63  MINIMUM_FELT_TEMPERATURE  object
 64  MAXIMUM_FELT_TEMPERATURE  object
 65  AVERAGE_FELT_TEMPERATURE  object
 66  distance                  object
 67  YAGIS_SİDDETİ             category
 68  SICAKLIK                  category
 69  RUZGAR                    category
 70  TRANSPORT_TYPE_ID         float64
 71  TRANSPORT_TYPE_DESC       object
 72  LINE                      object
 73  TRANSFER_TYPE_ID          int64
 74  TRANSFER_TYPE             object
 75  NUMBER_OF_PASSENGER       int64
 76  NUMBER_OF_PASSAGE         int64
 77  M1                        float64
 78  M2                        float64
 79  M3                        float64
 80  M1_P                      float64
 81  M2_P                      float64
 82  M3_P                      float64
dtypes: category(3), datetime64[ns](1), float64(7), int64(3), object(69)
memory usage: 3.4+ GB

In [47]:
import numpy as np
one_hot_yagıs = pd.get_dummies(data_ıst['YAGIS_SİDDETİ'])

data_ıst = data_ıst.join(one_hot_yagıs ,lsuffix=None, rsuffix=None)

In [20]:
data_ıst.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5542718 entries, 0 to 5542717
Data columns (total 86 columns):
 #   Column                    Dtype
---  ------                    -----
 0   DATE_TIME                 datetime64[ns]
 1   LONGITUDE                 object
 2   LATITUDE                  object
 3   GEOHASH                   object
 4   MINIMUM_SPEED             object
 5   MAXIMUM_SPEED             object
 6   AVERAGE_SPEED             object
 7   NUMBER_OF_VEHICLES        object
 8   Friday                    object
 9   Monday                    object
 10  Saturday                  object
 11  Sunday                    object
 12  Thursday                  object
 13  Tuesday                   object
 14  Wednesday                 object
 15  April                     object
 16  August                    object
 17  December                  object
 18  February                  object
 19  January                   object
 20  July                      object
 21  June                      object
 22  March                     object
 23  May                       object
 24  November                  object
 25  October                   object
 26  September                 object
 27  06                        object
 28  07                        object
 29  08                        object
 30  09                        object
 31  10                        object
 32  11                        object
 33  12                        object
 34  13                        object
 35  14                        object
 36  15                        object
 37  16                        object
 38  17                        object
 39  18                        object
 40  19                        object
 41  20                        object
 42  21                        object
 43  22                        object
 44  23                        object
 45  MINIMUM_TEMPERATURE       object
 46  MAXIMUM_TEMPERATURE       object
 47  AVERAGE_TEMPERATURE       object
 48  MINIMUM_HUMIDITY          object
 49  MAXIMUM_HUMIDITY          object
 50  AVERAGE_HUMIDITY          object
 51  MINIMUM_WIND              object
 52  MAXIMUM_WIND              object
 53  AVERAGE_WIND              object
 54  MINIMUM_DIRECTIONOFWIND   object
 55  MAXIMUM_DIRECTIONOFWIND   object
 56  AVERAGE_DIRECTIONOFWIND   object
 57  MINIMUM_PRECIPITATION     object
 58  MAXIMUM_PRECIPITATION     object
 59  AVERAGE_PRECIPITATION     object
 60  MINIMUM_ROAD_TEMPERATURE  object
 61  MAXIMUM_ROAD_TEMPERATURE  object
 62  AVERAGE_ROAD_TEMPERATURE  object
 63  MINIMUM_FELT_TEMPERATURE  object
 64  MAXIMUM_FELT_TEMPERATURE  object
 65  AVERAGE_FELT_TEMPERATURE  object
 66  distance                  object
 67  YAGIS_SİDDETİ             category
 68  SICAKLIK                  category
 69  RUZGAR                    category
 70  TRANSPORT_TYPE_ID         float64
 71  TRANSPORT_TYPE_DESC       object
 72  LINE                      object
 73  TRANSFER_TYPE_ID          int64
 74  TRANSFER_TYPE             object
 75  NUMBER_OF_PASSENGER       int64
 76  NUMBER_OF_PASSAGE         int64
 77  M1                        float64
 78  M2                        float64
 79  M3                        float64
 80  M1_P                      float64
 81  M2_P                      float64
 82  M3_P                      float64
 83  YAGISSIZ                  uint8
 84  HAFİF YAGIS               uint8
 85  SİDDETLİ YAGIS            uint8
dtypes: category(3), datetime64[ns](1), float64(7), int64(3), object(69), uint8(3)
memory usage: 3.5+ GB

In [48]:
data_ıst.drop(['LINE','TRANSFER_TYPE_ID','TRANSFER_TYPE','TRANSPORT_TYPE_DESC','TRANSPORT_TYPE_ID',],axis=1,inplace=True)

In [ ]:
data_ıst.info()

In [49]:
data_ıst.to_csv('df.csv')

In [50]:
data_ıst

,DATE_TIME,LONGITUDE,LATITUDE,GEOHASH,MINIMUM_SPEED,MAXIMUM_SPEED,AVERAGE_SPEED,NUMBER_OF_VEHICLES,Friday,Monday,...,NUMBER_OF_PASSAGE,M1,M2,M3,M1_P,M2_P,M3_P,YAGISSIZ,HAFİF YAGIS,SİDDETLİ YAGIS
0,2020-04-01 06:00:00,29.09729,41.047668,sxk9w0,8,43,27,26,0,0,...,185,50.0,50.0,0.0,47.837838,47.837838,0.000000,1,0,0
1,2020-04-01 06:00:00,29.09729,41.047668,sxk9w0,8,43,27,26,0,0,...,5382,20.0,30.0,50.0,19.851356,29.777035,49.628391,1,0,0
2,2020-04-01 06:00:00,29.09729,41.047668,sxk9w0,8,43,27,26,0,0,...,78,100.0,0.0,0.0,100.000000,0.000000,0.000000,1,0,0
3,2020-04-01 06:00:00,29.09729,41.047668,sxk9w0,8,43,27,26,0,0,...,154,50.0,20.0,30.0,50.000000,20.000000,30.000000,1,0,0
4,2020-04-01 06:00:00,29.09729,41.047668,sxk9w0,8,43,27,26,0,0,...,1076,0.0,100.0,0.0,0.000000,99.349442,0.000000,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2639422,2021-02-21 22:00:00,29.130249,41.025696,sxk9qu,6,108,65,78,0,0,...,619,50.0,20.0,30.0,49.838449,19.935380,29.903069,1,0,0
2639423,2021-02-21 22:00:00,29.130249,41.025696,sxk9qu,6,108,65,78,0,0,...,96,0.0,0.0,100.0,0.000000,0.000000,98.958333,1,0,0
2639424,2021-02-21 22:00:00,29.130249,41.025696,sxk9qu,6,108,65,78,0,0,...,775,0.0,0.0,100.0,0.000000,0.000000,99.741935,1,0,0
2639425,2021-02-21 22:00:00,29.130249,41.025696,sxk9qu,6,108,65,78,0,0,...,129,0.0,0.0,100.0,0.000000,0.000000,99.224806,1,0,0
2639426,2021-02-21 22:00:00,29.130249,41.025696,sxk9qu,6,108,65,78,0,0,...,293,100.0,0.0,0.0,99.658703,0.000000,0.000000,1,0,0